// API ACTIONS
export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';
export const SET_API_ERROR = 'SET_API_ERROR';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_PLAYLIST_DATA = 'SET_PLAYLIST_DATA';

// UI STATES: 
export const TOGGLE_LOADER = 'TOGGLE_LOADER';